### ISSUE TITLE
Questions to ask for 2021 data

### ISSUE THREAD

**Issue by santiaguf** [colombia-dev/data#8]
put here questions you would like to know from 2021 data. 
e.g:  how many people who work with foreign companies are happy with their salary

**Comment by santiaguf** [comment]
@fev4 @ssinuco @r-vasquez @manaranjoc @dobleuber

**Comment by santiaguf** [comment]
- What is the average salary per city.

**Comment by fev4** [comment]
- Is seniority correlated to income? Are there any outliers? In which areas? How has the avg income per seniority behaved in the community in the last three years.
- What are the languages with the most income? Avg income, standard deviation and median per language
- Is the data representative of Colombia's dev community in general or only representative for ColombiaDev (slack community)?
  - Does the salary data align with salary distribution found in StackOverflow's questionnaire?
- Does going through a bootcamp increase salaries? By how much? Avg. income per bootcamp-student vs non-bootcamp-student, compare vs previous years too.
- Do remote-jobs earn more? By how much?
- Is english important to earn more money? English-speakers vs non-english speakers. Also introduce level of english into the mix
- Does gender impact income? By how much?

**Comment by oscardavidiaz** [comment]
Hola, quisiera añadir estas dos preguntas:

1. ¿Cuál es la plataforma o medio por el cuál ha logrado vincularse laboralmente con más eficiencia?.
  Posibles respuestas:
    - Computrabajo
    - Linkedin
    - Agencia Publica de Empleo
    - Referido por un conocido
    - Postulación directa con la empresa
    - Otra, ¿Cuál?.

2. ¿Con qué frecuencia sueles cambiar de empleo?
  Posibles respuestas:
    - Entre 1 y 2 veces al año.
    - Cada 2 años
    - Cada 5 años

**Comment by fev4** [comment]
I can start with these questions. Not sure which visualizations we're gonna use but I can start playing around with the data in Tableau Public.

@santiaguf not sure for how long we'll have this issue open but I think 20 - 30 days is enough, as I think it's important to have something before the end of the year

**Comment by santiaguf** [comment]
I agree with you @fev4.
